#!/usr/bin/env python2
#
# Clean up uselsee containers.
#
# Copyright (c) 2016 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

import sys
import docker

def main():
    docker.Docker().clean()
    return 0

if __name__ == "__main__":
    sys.exit(main())
