#!/usr/bin/env python2
#
# Wrapper for "docker run" with automatical clean up if the execution is
# iterrupted.
#
# Copyright (c) 2016 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

import sys
import argparse
import docker

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--keep", action="store_true",
                        help="Don't remove image when the command completes")
    parser.add_argument("--quiet", action="store_true",
                        help="Run quietly unless an error occured")
    args, argv = parser.parse_known_args()
    return docker.Docker().run(argv, args.keep, quiet=args.quiet)

if __name__ == "__main__":
    sys.exit(main())
