#!/bin/bash -e
#
# Quick compiling test that everyone already does. But why not automate it?
#
# Copyright (c) 2016 Red Hat Inc.
#
# Authors:
#  Fam Zheng <famz@redhat.com>
#
# This work is licensed under the terms of the GNU GPL, version 2
# or (at your option) any later version. See the COPYING file in
# the top-level directory.

. common.rc

mkdir build
mkdir install
cd build
echo "Building"
build_qemu \
    --prefix="${pwd}/install" \
    --target-list="$(echo {x86_64,i386,arm,aarch64}-{softmmu,linux-user})"
echo "Check"
make check $MAKEFLAGS
echo "Install"
make install
