# -*- Mode: makefile -*-
#
# AArch64 specific tweaks

AARCH64_SRC=$(SRC_PATH)/tests/tcg/aarch64
VPATH 		+= $(AARCH64_SRC)

# we don't build any of the ARM tests
AARCH64_TESTS=$(filter-out $(ARM_TESTS), $(TESTS))
AARCH64_TESTS+=fcvt

fcvt: LDFLAGS+=-lm

run-fcvt: fcvt
	$(call run-test,$<,$(QEMU) $<, "$< on $(TARGET_NAME)")
	$(call diff-out,$<,$(AARCH64_SRC)/fcvt.ref)

AARCH64_TESTS += pauth-1 pauth-2
run-pauth-%: QEMU += -cpu max

AARCH64_TESTS += pauth-linux-test
# newer compilers use -mbranch-protection=pac-ret
pauth-linux-test: CFLAGS+=-msign-return-address=all
pauth-linux-test: linux-test.c
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $< -o $@ $(LDFLAGS)

TESTS:=$(AARCH64_TESTS)
