#
# linux-user TCG tests
#
# The Make is expected to be invoked in the ${BUILD_DIR} directory
# using the tests-tcg target
#
BUILD_DIR?=$(CURDIR)
include $(BUILD_DIR)/config-host.mak	# brings in SRC_PATH

UNAME_M := $(shell uname -m)
BUILD_UID = $(shell id -u)

tests-tcg: prepare $(UNAME_M)

prepare:
	mkdir -p $(BUILD_DIR)/$(UNAME_M)-linux-user/tests/

x86_64:
	cd $(BUILD_DIR)/x86_64-linux-user/tests/ && \
	make -f $(SRC_PATH)/tests/tcg/i386/Makefile

i386:
	cd $(BUILD_DIR)/i386-linux-user/tests/ && \
	make -f $(SRC_PATH)/tests/tcg/i386/Makefile

arm-tcg-tests: docker-image-debian-multiarch-cross
	mkdir -p $(BUILD_DIR)/arm-linux-user/tests
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/arm-linux-user/tests \
		-e CROSS_CC="arm-linux-gnueabihf-gcc" \
		qemu:debian-multiarch-cross \
		make -f ../../tests/tcg/misc/Makefile
	docker run --rm -it -v $(SRC_PATH):$(SRC_PATH) \
		-v $(BUILD_DIR):$(BUILD_DIR) \
		--user $(BUILD_ID):$(BUILD_ID) \
		-w $(BUILD_DIR)/arm-linux-user/tests \
		-e CROSS_CC="arm-linux-gnueabihf-gcc" \
		qemu:debian-multiarch-cross \
		make -f ../../tests/tcg/arm/Makefile

aarch64:
	cd $(BUILD_DIR)/aarch64-linux-user/tests/ && \
	make -f $(SRC_PATH)/tests/tcg/arm/Makefile

.PHONY: tests-tcg
