UNAME_P := $(shell uname -p)

tests-tcg: misc

x86_64:
	cd $(SRC_PATH)/tests/tcg/i386 && make
i386:
	cd $(SRC_PATH)/tests/tcg/i386 && make

arm:
	cd $(SRC_PATH)/tests/tcg/arm && make
aarch64:
	cd $(SRC_PATH)/tests/tcg/arm && make

misc:
	cd $(SRC_PATH)/tests/tcg/misc && make
	make $(UNAME_P)

.PHONY: tests-tcg

