# Makefile.include for all ARM targets
#
# We don't have any bigendian build tools so we only use this for armhf

ifeq ($(TARGET_NAME),arm)
ifeq ($(CONFIG_SOFTMMU),y)
DOCKER_IMAGE=fedora-arm-cross
DOCKER_CROSS_COMPILER=arm-linux-gnu-gcc
else
DOCKER_IMAGE=debian-armhf-cross
DOCKER_CROSS_COMPILER=arm-linux-gnueabihf-gcc
endif
endif
