# -*- Mode: makefile -*-
#
# ARM SoftMMU tests - included from tests/tcg/Makefile for CONFIG_SOFTMMU
#

ARM_SRC=$(SRC_PATH)/tests/tcg/arm
VPATH += $(ARM_SRC)

TESTS += test-armv6m-undef

%.o: %.S %.ld
	$(CC) -march=armv6t2 -nostdlib -Wl,--build-id=none -x assembler-with-cpp -T $(patsubst %.S,%.ld,$<) -x assembler-with-cpp -o $@ $<

%: %.o
	$(OBJCOPY) -O ihex $< $@

run-test-armv6m-undef: test-armv6m-undef
	$(QEMU) -semihosting -display none -M microbit -device loader,file=$<
