#! /bin/sh
# Construct a target device config file from a default, pulling in any
# files from include directives. The include files are inlined in the order
# they are found in the source file so you can reverse a sub-set of
# settings afterwards.

dest=$1.tmp
dep=`dirname $1`-`basename $1`.d
src=$2
src_dir=`dirname $src`
all_includes=

process_file () {
    local in=$1
    local out=$2
    while read first second; do
        if [ "$first" = "include" ]; then
            local inc="$src_dir/$second"
            all_includes="$all_includes $inc"
            echo "# include file: $inc" >> $out
            process_file $inc $out
            echo "# end of include: $inc" >> $out
        else
            if [ "x$second" = "x" ]; then
                echo $first >> $out
            else
                echo "$first $second" >> $out
            fi
        fi
    done < $in
}

echo "# This file is auto-generated by make_device_config.sh" > $dest
process_file $src $dest
echo "$1: $all_includes" > $dep
